name: Run Lynet

on: push

jobs:
  run-lynet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Run Lynet
        run: npm run lynet
        env:
          LYNET_TOKEN: ${{ secrets.LYNET_TOKEN }}